cernopendata/modules/pages/views.py
# -*- coding: utf-8 -*-
#
# This file is part of CERN Open Data Portal.
# Copyright (C) 2017, 2018 CERN.
#
# CERN Open Data Portal is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Open Data Portal is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CERN Open Data Portal; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Pages for CERN Open Data Portal."""

import json

import pkg_resources
from flask import (
    Blueprint,
    Response,
    abort,
    current_app,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from invenio_i18n import lazy_gettext as _
from jinja2.exceptions import TemplateNotFound
from markupsafe import escape
from speaklater import make_lazy_string
from webargs.flaskparser import use_args

from cernopendata.cold_storage.schemas import (
    TransferRequestQuerySchema,
    TransferRequestSchema,
)
from cernopendata.cold_storage.service import RequestService

from .utils import FeaturedArticlesSearch

blueprint = Blueprint(
    "cernopendata_pages",
    __name__,
    template_folder="templates",
    static_folder="static",
)


@blueprint.errorhandler(TemplateNotFound)
def template_not_found(err):
    """Log missing template."""
    current_app.logger.exception("Please check missing template.")
    abort(404)
    # return 'Template not found!', 404


def lazy_title(text, *args):
    """Make tranlated string with escaped values from request view args."""
    return _(
        text,
        **{
            key: make_lazy_string(lambda: escape(request.view_args.get(key, "")))
            for key in args
        }
    )


@blueprint.route("/")
def index():
    """Home Page."""
    results = []
    try:
        results = (
            FeaturedArticlesSearch().sort("-date_published")[:6].execute().hits.hits
        )
    except Exception:
        pass
    return render_template(
        "cernopendata_pages/front/index.html", featured_articles=results
    )


@blueprint.route("/robots.txt")
def robots():
    """Render robots page."""
    with open("cernopendata/templates/cernopendata_pages/robots.txt") as f:
        return Response(f.read(), mimetype="text/plain")


@blueprint.route("/md/debug", methods=["HEAD", "GET"])
def md_debug():
    """Test Markdown rendering of a page.

    Route for quicker previewing markdown during development.
    During edit replace contents of `cernopendata/static/test_data/debug.md`
    and just refresh the view.
    I.e. there is no need to re-populate db every time a change is made.

    If DEBUG is not set this will redirect to homepage.

    Command `cernopendata collect -v` has to be run everytime
    there is a change in static resources.

    """
    if current_app.config.get("DEBUG"):
        f = open("cernopendata/static/test_data/debug.md", "r")
        # return render_template_string(
        #     u"{{ text|markdown }}", text=f.read().decode("utf-8"))
        return render_template(
            "cernopendata_pages/md_template.html", content=f.read().decode("utf-8")
        )
    else:
        return redirect("/")


@blueprint.route("/visualise/events")
def visualise_events_landing():
    """Display landing page."""
    try:
        return render_template("cernopendata_pages/visualise_events.html")
    except TemplateNotFound:
        return abort(404)


@blueprint.route("/visualise/events/<string:experiment>")
@blueprint.route("/visualise/events/<string:experiment>/<int:eventid>")
def visualise_events(experiment="cms", eventid=None):
    """Display visualisations."""
    # if experiment == 'opera':
    #     abort(404)
    try:
        return render_template(
            "cernopendata_pages/visualise_events_{}.html".format(experiment),
            eventid=eventid,
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


@blueprint.route("/visualise/histograms")
@blueprint.route("/visualise/histograms/<string:experiment>")
def visualise_histograms(experiment="cms"):
    """Display histograms."""
    try:
        return render_template(
            "cernopendata_pages/visualise_histograms.html",
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


# FIXME quick fix
@blueprint.route("/record/<recid>/")
def record_redirect(recid):
    """Redirect to deal with trailing slash."""
    return redirect("/record/{}".format(recid))


@blueprint.route("/glossary")
def glossary():
    """Display glossary terms."""
    return redirect("/search?f=type%3AGlossary&sort=title")


@blueprint.route("/glossary/json")
def glossary_json():
    """Fetch glossary json."""
    filepath = pkg_resources.resource_filename(
        "cernopendata.modules.fixtures", "data/terms/terms.json"
    )
    with open(filepath, "r") as f:
        glossary = json.load(f)
    return jsonify(glossary)


@blueprint.route("/experiments")
@blueprint.route("/resources")
@blueprint.route("/research")
@blueprint.route("/research" '/<any("lhcb","alice","atlas"):experiment>')
@blueprint.route("/resources" '/<any("cms","lhcb","alice","atlas"):experiment>')
@blueprint.route("/collection/<string:collection>")
@blueprint.route(
    '/<any("getting-started","getstarted", "vm","news",'
    '"datasets","documentation","software"):page>'
)
@blueprint.route(
    '/<any("getting-started","getstarted","vm"):page>'
    '/<any("opera", "atlas"):experiment>'
)
def faceted_search(page=None, experiment=None, collection=None):
    """Faceted search view.

    To add a new page:
        add url to blueprint.route
        add mapping, which (filter,val,search_endpoint)
            should be used to filter records

    """
    facets = [x for x in locals().values() if x]
    filters = {}

    filter_map = {
        "documentation": ("type", "Documentation"),
        "software": ("type", "Software"),
        "datasets": ("type", "Dataset"),
        "getting-started": ("tags", "Getting Started"),
        "getstarted": ("tags", "Getting Started"),
        "news": ("type", "News"),
        "vm": ("tags", "VM"),
        "cms": ("experiment", "CMS"),
        "alice": ("experiment", "ALICE"),
        "atlas": ("experiment", "ATLAS"),
        "lhcb": ("experiment", "LHCb"),
        "opera": ("experiment", "OPERA"),
        "data-policies": ("collections", "Data-Policies"),
        "alice-derived-datasets": ("collections", "ALICE-Derived-Datasets"),
        "alice-reconstructed-data": ("collections", "ALICE-Reconstructed-Data"),
        "alice-learning-resources": ("collections", "ALICE-Learning-Resources"),
        "alice-tools": ("collections", "ALICE-Tools"),
        "atlas-derived-datasets": ("collections", "ATLAS-Derived-Datasets"),
        "atlas-higgs-challenge-2014": ("collections", "ATLAS-Higgs-Challenge-2014"),
        "atlas-simulated-datasets": ("collections", "ATLAS-Simulated-Datasets"),
        "atlas-learning-resources": ("collections", "ATLAS-Learning-Resources"),
        "atlas-tools": ("collections", "ATLAS-Tools"),
        "author-lists": ("collections", "Author-Lists"),
        "cms-condition-data": ("collections", "CMS-Condition-Data"),
        "cms-configuration-files": ("collections", "CMS-Configuration-Files"),
        "cms-derived-datasets": ("collections", "CMS-Derived-Datasets"),
        "cms-luminosity-information": ("collections", "CMS-Luminosity-Information"),
        "cms-open-data-instructions": ("collections", "CMS-Open-Data-Instructions"),
        "cms-learning-resources": ("collections", "CMS-Learning-Resources"),
        "cms-primary-datasets": ("collections", "CMS-Primary-Datasets"),
        "cms-simulated-datasets": ("collections", "CMS-Simulated-Datasets"),
        "cms-tools": ("collections", "CMS-Tools"),
        "cms-trigger-information": ("collections", "CMS-Trigger-Information"),
        "cms-validated-runs": ("collections", "CMS-Validated-Runs"),
        "cms-validation-utilities": ("collections", "CMS-Validation-Utilities"),
        "lhcb-derived-datasets": ("collections", "LHCb-Derived-Datasets"),
        "lhcb-learning-resources": ("collections", "LHCb-Learning-Resources"),
        "lhcb-tools": ("collections", "LHCb-Tools"),
        "opera-detector-events": ("collections", "OPERA-Detector-Events"),
        "opera-electronic-detector-datasets": (
            "collections",
            "OPERA-Electronic-Detector-Datasets",
        ),
        "opera-emulsion-detector-datasets": (
            "collections",
            "OPERA-Emulsion-Detector-Datasets",
        ),
    }

    for facet in facets:
        _filter = filter_map.get(facet) or abort(404)
        filters[_filter[0]] = _filter[1]

    return redirect(url_for("invenio_search_ui.search", **filters))


@blueprint.route("/education")
@blueprint.route("/education" '/<any("lhcb","opera","alice","atlas"):experiment>')
def education_pages(experiment=None):
    """Education pages."""
    collections = {
        "education": {
            "alice": [
                "ALICE-Derived-Datasets",
                "ALICE-Reconstructed-Data",
                "ALICE-Tools",
                "ALICE-Learning-Resources",
            ],
            "atlas": [
                "ATLAS-Derived-Datasets",
                "ATLAS-Learning-Resources",
                "ATLAS-Tools",
                "ATLAS-Higgs-Challenge-2014",

cernopendata/templates/cernopendata_pages/front/index.html
{%- extends config.BASE_TEMPLATE %}


{%- block css %}
    {{ super() }}
{%- endblock css %}

{%- block page_header %}
{% include 'cernopendata_theme/header_index.html' %}
{%- endblock page_header %}
{%- block page_body %}
        {% include 'cernopendata_pages/front/main.html' %}
        {% include 'cernopendata_pages/front/lva.html' %}
        {% include 'cernopendata_pages/front/news.html' %}
{%- endblock %}

{%- block javascript %}
    {{ super() }}
{%- endblock javascript %}

cernopendata/templates/cernopendata_pages/front/lva.html
<div class="homepage-section section lva" id="lva" data-anchor="lva">
    <div class="container lva-container">
        <div class="lva-item-container">
            <div class="lva-item">
                <header>
                    <h3 class="row">Learn</h3>
                    <div class="row">
                        <div class="text">
                            Discover the world of open data from particle physics
                        </div>
                    </div>
                </header>

                <div class="body">
                    <ul>
                        <li class="row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='welcome')}}">Welcome to our
                                updated portal</a>
                        </li>
                        <li class="row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='cms-guide-for-education')}}">CMS
                                Guide to education use of CMS Open Data</a>
                        </li>
                        <li class="row">
                            <a
                                href="{{url_for('invenio_records_ui.docid', pid_value='cms-summer-student-report-2017')}}">Improving
                                educational content with high school teachers: A
                                field report from our summer students</a>
                        </li>
                        <li class="row">
                            <a href="{{url_for('cernopendata_pages.glossary')}}">Glossary</a>
                        </li>
                    </ul>
                </div>

                <div class="more">
                    <a href="/search?type=Documentation">Documentation</a>
                </div>
            </div>
        </div>
        <div id="visualize" class="lva-item-container">
            <div class="lva-item">
                <header>
                    <h3 class="row">Visualise</h3>
                    <div class="row">
                        <div class="text">
                            Explore detector events and run basic histogramming
                        </div>
                    </div>
                </header>

                <div class="body">
                    <ul>
                        <li>
                            <a href="{{url_for('cernopendata_pages.visualise_events', experiment='cms')}}">CMS Event
                                Display</a>
                        </li>
                        <li>
                            <a href="{{url_for('cernopendata_pages.visualise_events', experiment='opera')}}">OPERA Event
                                Display</a>
                        </li>
                        <li>
                            <a href="{{url_for('cernopendata_pages.visualise_histograms')}}">CMS Histograms</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="lva-item-container">
            <div class="lva-item">
                <header>
                    <h3 class="row">Analyse</h3>
                    <div class="row">
                        <div class="text">
                            Run your own physics analyses, start virtual machines
                        </div>
                    </div>
                </header>

                <div class="body">
                    <ul>
                        <li class="row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='cms-guide-for-research')}}">CMS
                                Guide to research use of CMS Open Data</a>
                        </li>
                        <li class="row">
                            <a
                                href="{{url_for('invenio_records_ui.docid', pid_value='atlas-higgs-machine-learning-challenge')}}">ATLAS
                                Higgs Machine Learning Challenge</a>
                        </li>
                        <li class="row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='lhcb-getting-started')}}">Getting
                                Started with LHCb Open Data</a>
                        </li>
                        <li class="row">
                            <a href="{{url_for('invenio_records_ui.docid', pid_value='alice-getting-started')}}">Getting
                                Started with ALICE Open Data</a>
                        </li>
                    </ul>
                </div>
                <div class="more">
                    <a href="/research">Further documents</a>
                </div>
            </div>
        </div>
    </div>
    <div class="cod-scroll">
        <div class="icon">
            <a href="#news">
                <img src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}" alt=""/>
                <span>News</span>
                <img src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}" alt=""/>
            </a>
        </div>
    </div>
</div>

cernopendata/templates/cernopendata_pages/front/main.html
<div
  class="homepage-section main section align-items-center"
  data-anchor="main"
>
  <div class="ui container container-main">
    <div class="cod-banner row">
      <h2>
        <span>
          Explore more than <span><strong>five petabytes</strong></span> <br />
          <span class="scnd-line"
            >of open data from particle physics!</span
          ></span
        >
      </h2>
    </div>
    <div class="cod-search row">
      <form
        class="search-form container"
        action="{{config.THEME_SEARCH_ENDPOINT}}"
        role="search"
      >
        <input
          autofocus
          type="text"
          class="form-control search"
          name="q"
          aria-label="search"
        />
        <div>
          <button type="submit">Search</button>
          <div class="cod-home-image">
            <img
              src="{{url_for('static', filename='assets/img/header-image.svg')}}"
              alt=""
            />
          </div>
        </div>
      </form>
      <div class="search-examples row">
        <span class="example-title">search examples:</span>
        <a href="/search?subtype=Collision&type=Dataset">collision datasets</a>,
        <a href="/search?keywords=education">keywords:education</a>,
        <a href="/search?collision_energy=7TeV">energy:7TeV</a>
      </div>
    </div>

    <div class="cod-collections row">
      <div class="collections-col">
        <header><span>Explore</span></header>
        <ul>
          <li><a href="/search?type=Dataset">datasets</a></li>
          <li><a href="/search?type=Software">software</a></li>
          <li><a href="/search?type=Environment">environments</a></li>
          <li><a href="/search?type=Documentation">documentation</a></li>
        </ul>
      </div>
      <div class="collections-col">
        <header><span>Focus on</span></header>
        <ul>
          {% for exp in experiments_display.values() %}
            <li><a href="/search?experiment={{ exp.name }}">{{ exp.name }}</a></li>
          {% endfor %}
          <li><a href="/search?keywords=datascience">Data Science</a></li>
        </ul>
      </div>
    </div>
    <div class="cod-scroll row">
      <div class="icon">
        <a href="#lva">
          <img
            src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}"
            alt=""
          />
          <span>Get started</span>
          <img
            src="{{url_for('static', filename='assets/img/mouse-scrolling.png')}}"
            alt=""
          />
        </a>
      </div>
    </div>
  </div>
</div>

cernopendata/templates/cernopendata_pages/front/news.html
<div class="homepage-section news section" id="news" data-anchor="news">
    <div class="ui container fluid">
        <div class="news-header">
            <h3 class="">News & Updates</h3>
        </div>
        <div class="ui grid news-wrapper">
            {% for article in featured_articles %}
            {% set article = article._source %}
            <div class="news-item ui five wide column card-body">
                <div class="news-card">
                    <p class="date-author-small">
                        {{ article.date_published or '-' }} by
                        {{ article.author or 'Open Data Portal team'}}
                    </p>
                    <div>
                        <h4>
                            <a href="/docs/{{article.slug}}">{{article.title}}</a>
                        </h4>
                    </div>
                    <div class="tags-box">
                        <a href="/search?type={{article.type.primary}}"
                            class="ui label blue-tag">
                            {{article.type.primary }}
                        </a>
                        {% if article.type.secondary %}
                        {% for subtype in article.type.secondary %}
                        <a href="/search?subtype={{subtype}}" class="ui label teal">{{ subtype }}</a>
                        {% endfor %}
                        {% endif %}
                        {% for tag in article.tags %}
                        <a href="/search?tags={{tag}}" class="ui label">{{ tag }}</a>
                        {% endfor %}
                        {% for exp in article.experiment %}
                        <a href="/search?experiment={{exp}}"
                            class="ui label orange-tag">
                            {{ exp }}
                        </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="more-container">
            <div class="more">
                <a href="{{url_for('invenio_search_ui.search', f = 'type:News') }}">All news</a>
            </div>
        </div>
    </div>
</div>