cernopendata/modules/pages/views.py
# -*- coding: utf-8 -*-
#
# This file is part of CERN Open Data Portal.
# Copyright (C) 2017, 2018 CERN.
#
# CERN Open Data Portal is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Open Data Portal is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CERN Open Data Portal; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

"""Pages for CERN Open Data Portal."""

import json

import pkg_resources
from flask import (
    Blueprint,
    Response,
    abort,
    current_app,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from invenio_i18n import lazy_gettext as _
from jinja2.exceptions import TemplateNotFound
from markupsafe import escape
from speaklater import make_lazy_string
from webargs.flaskparser import use_args

from cernopendata.cold_storage.schemas import (
    TransferRequestQuerySchema,
    TransferRequestSchema,
)
from cernopendata.cold_storage.service import RequestService

from .utils import FeaturedArticlesSearch

blueprint = Blueprint(
    "cernopendata_pages",
    __name__,
    template_folder="templates",
    static_folder="static",
)


@blueprint.errorhandler(TemplateNotFound)
def template_not_found(err):
    """Log missing template."""
    current_app.logger.exception("Please check missing template.")
    abort(404)
    # return 'Template not found!', 404


def lazy_title(text, *args):
    """Make tranlated string with escaped values from request view args."""
    return _(
        text,
        **{
            key: make_lazy_string(lambda: escape(request.view_args.get(key, "")))
            for key in args
        }
    )


@blueprint.route("/")
def index():
    """Home Page."""
    results = []
    try:
        results = (
            FeaturedArticlesSearch().sort("-date_published")[:6].execute().hits.hits
        )
    except Exception:
        pass
    return render_template(
        "cernopendata_pages/front/index.html", featured_articles=results
    )


@blueprint.route("/robots.txt")
def robots():
    """Render robots page."""
    with open("cernopendata/templates/cernopendata_pages/robots.txt") as f:
        return Response(f.read(), mimetype="text/plain")


@blueprint.route("/md/debug", methods=["HEAD", "GET"])
def md_debug():
    """Test Markdown rendering of a page.

    Route for quicker previewing markdown during development.
    During edit replace contents of `cernopendata/static/test_data/debug.md`
    and just refresh the view.
    I.e. there is no need to re-populate db every time a change is made.

    If DEBUG is not set this will redirect to homepage.

    Command `cernopendata collect -v` has to be run everytime
    there is a change in static resources.

    """
    if current_app.config.get("DEBUG"):
        f = open("cernopendata/static/test_data/debug.md", "r")
        # return render_template_string(
        #     u"{{ text|markdown }}", text=f.read().decode("utf-8"))
        return render_template(
            "cernopendata_pages/md_template.html", content=f.read().decode("utf-8")
        )
    else:
        return redirect("/")


@blueprint.route("/visualise/events")
def visualise_events_landing():
    """Display landing page."""
    try:
        return render_template("cernopendata_pages/visualise_events.html")
    except TemplateNotFound:
        return abort(404)


@blueprint.route("/visualise/events/<string:experiment>")
@blueprint.route("/visualise/events/<string:experiment>/<int:eventid>")
def visualise_events(experiment="cms", eventid=None):
    """Display visualisations."""
    # if experiment == 'opera':
    #     abort(404)
    try:
        return render_template(
            "cernopendata_pages/visualise_events_{}.html".format(experiment),
            eventid=eventid,
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


@blueprint.route("/visualise/histograms")
@blueprint.route("/visualise/histograms/<string:experiment>")
def visualise_histograms(experiment="cms"):
    """Display histograms."""
    try:
        return render_template(
            "cernopendata_pages/visualise_histograms.html",
            experiment=experiment,
        )
    except TemplateNotFound:
        return abort(404)


# FIXME quick fix
@blueprint.route("/record/<recid>/")
def record_redirect(recid):
    """Redirect to deal with trailing slash."""
    return redirect("/record/{}".format(recid))


@blueprint.route("/glossary")
def glossary():
    """Display glossary terms."""
    return redirect("/search?f=type%3AGlossary&sort=title")


@blueprint.route("/glossary/json")
def glossary_json():
    """Fetch glossary json."""
    filepath = pkg_resources.resource_filename(
        "cernopendata.modules.fixtures", "data/terms/terms.json"
    )
    with open(filepath, "r") as f:
        glossary = json.load(f)
    return jsonify(glossary)


@blueprint.route("/experiments")
@blueprint.route("/resources")
@blueprint.route("/research")
@blueprint.route("/research" '/<any("lhcb","alice","atlas"):experiment>')
@blueprint.route("/resources" '/<any("cms","lhcb","alice","atlas"):experiment>')
@blueprint.route("/collection/<string:collection>")
@blueprint.route(
    '/<any("getting-started","getstarted", "vm","news",'
    '"datasets","documentation","software"):page>'
)
@blueprint.route(
    '/<any("getting-started","getstarted","vm"):page>'
    '/<any("opera", "atlas"):experiment>'
)
def faceted_search(page=None, experiment=None, collection=None):
    """Faceted search view.

    To add a new page:
        add url to blueprint.route
        add mapping, which (filter,val,search_endpoint)
            should be used to filter records

    """
    facets = [x for x in locals().values() if x]
    filters = {}

    filter_map = {
        "documentation": ("type", "Documentation"),
        "software": ("type", "Software"),
        "datasets": ("type", "Dataset"),
        "getting-started": ("tags", "Getting Started"),
        "getstarted": ("tags", "Getting Started"),
        "news": ("type", "News"),
        "vm": ("tags", "VM"),
        "cms": ("experiment", "CMS"),
        "alice": ("experiment", "ALICE"),
        "atlas": ("experiment", "ATLAS"),
        "lhcb": ("experiment", "LHCb"),
        "opera": ("experiment", "OPERA"),
        "data-policies": ("collections", "Data-Policies"),
        "alice-derived-datasets": ("collections", "ALICE-Derived-Datasets"),
        "alice-reconstructed-data": ("collections", "ALICE-Reconstructed-Data"),
        "alice-learning-resources": ("collections", "ALICE-Learning-Resources"),
        "alice-tools": ("collections", "ALICE-Tools"),
        "atlas-derived-datasets": ("collections", "ATLAS-Derived-Datasets"),
        "atlas-higgs-challenge-2014": ("collections", "ATLAS-Higgs-Challenge-2014"),
        "atlas-simulated-datasets": ("collections", "ATLAS-Simulated-Datasets"),
        "atlas-learning-resources": ("collections", "ATLAS-Learning-Resources"),
        "atlas-tools": ("collections", "ATLAS-Tools"),
        "author-lists": ("collections", "Author-Lists"),
        "cms-condition-data": ("collections", "CMS-Condition-Data"),
        "cms-configuration-files": ("collections", "CMS-Configuration-Files"),
        "cms-derived-datasets": ("collections", "CMS-Derived-Datasets"),
        "cms-luminosity-information": ("collections", "CMS-Luminosity-Information"),
        "cms-open-data-instructions": ("collections", "CMS-Open-Data-Instructions"),
        "cms-learning-resources": ("collections", "CMS-Learning-Resources"),
        "cms-primary-datasets": ("collections", "CMS-Primary-Datasets"),
        "cms-simulated-datasets": ("collections", "CMS-Simulated-Datasets"),
        "cms-tools": ("collections", "CMS-Tools"),
        "cms-trigger-information": ("collections", "CMS-Trigger-Information"),
        "cms-validated-runs": ("collections", "CMS-Validated-Runs"),
        "cms-validation-utilities": ("collections", "CMS-Validation-Utilities"),
        "lhcb-derived-datasets": ("collections", "LHCb-Derived-Datasets"),
        "lhcb-learning-resources": ("collections", "LHCb-Learning-Resources"),
        "lhcb-tools": ("collections", "LHCb-Tools"),
        "opera-detector-events": ("collections", "OPERA-Detector-Events"),
        "opera-electronic-detector-datasets": (
            "collections",
            "OPERA-Electronic-Detector-Datasets",
        ),
        "opera-emulsion-detector-datasets": (
            "collections",
            "OPERA-Emulsion-Detector-Datasets",
        ),
    }

    for facet in facets:
        _filter = filter_map.get(facet) or abort(404)
        filters[_filter[0]] = _filter[1]

    return redirect(url_for("invenio_search_ui.search", **filters))


@blueprint.route("/education")
@blueprint.route("/education" '/<any("lhcb","opera","alice","atlas"):experiment>')
def education_pages(experiment=None):
    """Education pages."""
    collections = {
        "education": {
            "alice": [
                "ALICE-Derived-Datasets",
                "ALICE-Reconstructed-Data",
                "ALICE-Tools",
                "ALICE-Learning-Resources",
            ],
            "atlas": [
                "ATLAS-Derived-Datasets",
                "ATLAS-Learning-Resources",
                "ATLAS-Tools",
                "ATLAS-Higgs-Challenge-2014",

cernopendata/templates/cernopendata_theme/breadcrumbs.html
{%- if breadcrumbs|length > 1 %}
  <ol class="breadcrumb custom-breadcrumb">
    {%- for breadcrumb in breadcrumbs %}
    {%- if loop.last %}
    <li class="breadcrumb-item active">
      {{ breadcrumb.text|safe }}
    </li>
    {%- else %}
    <li class="breadcrumb-item">
      <a href="{{ breadcrumb.url }}">
        {{ breadcrumb.text|safe }}
      </a>
    </li>
    {%- endif %}
    {%- endfor %}
  </ol>
{%- endif %}

cernopendata/templates/cernopendata_theme/footer.html
<section class="footer">
  <div class="ui grid padded">
    <div class="row">
      <div class="six wide column">
        <div class="ui list horizontal logos">
          {% for id, exp in experiments_display.items() %}
          <div class="item">
            <a href="https://{{ exp.url }}">
              <img
                src="{{ url_for('static', filename='img/experiments/{}.gif'.format(id)) }}"
                alt="{{ exp.name }} experiment"
                width="{{ exp.get('width', auto) }}"
                height="{{ exp.get('height', 55) }}"
              />
            </a>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="four wide column centered stretched middle aligned">
        {% set year = None %}
        <div class="ui list horizontal copyright ">
          <div class="item">
            © CERN, 2014–{{year|get_year}} &middot;
          </div>
          <div class="item">
            <a href="/terms-of-use">Terms of Use</a> &middot;
          </div>
          <div class="item">
            <a href="/privacy-policy">Privacy Policy</a> &middot;
          </div>
          <div class="item">
            <a href="https://opendata-forum.cern.ch/">Help</a> &middot;
          </div>
          <div class="item">
            <a href="https://github.com/cernopendata/opendata.cern.ch/issues"
              >GitHub</a
            >
            &middot;
          </div>
          <div class="item">
            <a href="https://twitter.com/cernopendata">Twitter</a> &middot;
          </div>
          <div class="item">
            <a href="mailto:opendata-support@cern.ch">Email</a>
          </div>
        </div>
      </div>
      <div class="six wide column stretched align-items-end">
        <div class="auto-column-grid">
          <div >
            <a href="https://inveniosoftware.org/">Powered by Invenio</a><br>
            Open Data Portal v{{ opendata_version }}
          </div>
          <div>
            <a href="https://www.cern.ch">
              <img
                src="{{url_for('static', filename='assets/img/cern.svg')}}"
                width="80px"
                alt="CERN"
              />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

cernopendata/templates/cernopendata_theme/header.html
{%- extends "invenio_theme/header.html" %}
{%- block navbar %}
<nav class="navbar-custom">
  <a class="navbar-brand" href="{{ url_for('cernopendata_pages.index') }}">
    <img src="{{ url_for('static', filename='assets/img/logo_blue.png') }}" width="115" alt="Open Data CERN">
  </a>

  <ul class="link-menu">
    {%- if not current_user.is_authenticated %}
      <li class="item"><a href="/login">Login</a></li>
    {%- else %}
      <li class="ui dropdown" >
        <span class="navbar-item">
          <span>{{ current_user.email|truncate(31,true) }}<i class="dropdown icon"></i></span>
        </span>
        <div class="menu dropdown-items">
          <div class="item"><a href="/releases/atlas">Curate ATLAS data</a></div>
          <div class="item"><a href="/logout">Logout</a></div>
        </div>
      </li>

      </span>
    {%- endif %}
    <li class="ui dropdown">
      <span class="navbar-item">
        <span>Help<i class="dropdown icon"></i></span>
      </span>
      <div class="menu dropdown-items">
        <div class="item"><a href="https://opendata-forum.cern.ch/">Discussion forum</a></div>
        <div class="item"><a href="/docs/cod-search-tips">Search tips</a></div>
      </div>
    </li>
    <li class="ui dropdown">
      <span class="navbar-item">
        <span>About<i class="dropdown icon"></i></span>
      </span>
      <div class="menu dropdown-items">
        <div class="item"><a href="/docs/about">CERN Open Data</a></div>
        {% for id, exp in experiments_display.items() if not exp.no_opendata_docs %}
          <div class="item"><a href="/docs/about-{{ id }}">{{ exp.name }}</a></div>
        {% endfor %}
        <div class="item"><a href="/search?type=Glossary&sort=title">Glossary</a></div>
      </div>
    </li>
    <span class="menu-icon"/>
  </ul>
</nav>

{%- endblock navbar %}

{%- block breadcrumbs %}
{%- include "cernopendata_theme/breadcrumbs.html" %}
{%- endblock breadcrumbs %}

cernopendata/templates/cernopendata_theme/header_index.html
{%- extends "cernopendata_theme/header.html" %}

{% block search_bar %}{% endblock search_bar %}

cernopendata/templates/cernopendata_theme/page.html
{% extends 'invenio_theme/page.html' %}

{% block css %}
    {{ super() }}
    {{ webpack['cernopendata_css.css'] }}
    {{ webpack['glossary_css.css'] }}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{%- endblock css %}

{%- block bypasslinks %}
{%- endblock bypasslinks %}

{%- block body_inner %}
  <!--Wrapper for page content to push down footer-->
  <div class="footer-wrap background" role="main">
    <!-- Begin page content -->
    <div>
    {%- block page_header %}
    {% include 'cernopendata_theme/header.html' %}
    {%- endblock page_header %}
      {% if config['ANNOUNCEMENT_BANNER_MESSAGE'] %}
      <div class="ui bottom attached small warning message">
        <p>{{ config['ANNOUNCEMENT_BANNER_MESSAGE'] | safe }}</p>
      </div>
      {% endif %}
    </div>

      {%- block page_body %}
      {%- block page_body_top %}{%- endblock page_body_top %}

      {%- endblock page_body %}

    <!-- End page content -->
    <div class="footer-push"></div> <!-- Make room for footer -->

  </div>

  {%- block page_footer %}
  {% include "cernopendata_theme/footer.html" %}
  {%- endblock page_footer %}

{%- endblock body_inner %}

{%- block javascript %}
  {{ super() }}
  {{ webpack['cernopendata_js.js'] }}
  {{ webpack['glossary_js.js'] }}
  {# {% assets "cernopendata_search_js" %}<script src="{{ ASSET_URL }}"></script>{% endassets %} #}

  {%- block javascript_glossary %}

    <script>
        jquery(document).ready(function () {
          jquery('body').glossary('/glossary/json');
        });
    </script>
  {% endblock %}

  {%- block mathjax_support %}
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        jax: ["input/TeX", "output/HTML-CSS"],
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"] ],
          displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
          processEscapes: true
        },
        "HTML-CSS": { availableFonts: ["TeX"], matchFontHeight: false }
      });
    </script>

    <script type="text/javascript" src="{{ config['THEME_MATHJAX_CDN'] }}"></script>
  {% endblock %}

  {%- block jsonld_serialization %}{%- endblock jsonld_serialization %}

{% endblock %}

{%- block trackingcode %}
  {% include "cernopendata_theme/trackingcode.html" %}
{%- endblock %}

cernopendata/templates/cernopendata_theme/trackingcode.html
{%- if config.THEME_PIWIK_ID %}
<script type="text/javascript">
 var pkBaseURL = (("https:" == document.location.protocol) ? "https://piwik.web.cern.ch/" : "http://piwik.web.cern.ch/");
 document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
          try {
              var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", "{{config.THEME_PIWIK_ID}}");
              piwikTracker.trackPageView();
              piwikTracker.enableLinkTracking();
          } catch( err ) {}
</script><noscript><p><img src="http://piwik.web.cern.ch/piwik.php?idsite={{config.THEME_PIWIK_ID}}" style="border:0" alt="" /></p></noscript>
{%- endif %}